com.discordsrv.core:
    debug:
        Debugger:
            debug: false
    discord:
        DSRVJDABuilder:
            token: 'THIS IS YOUR TOKEN'
        commands:
            AuthenticateCommand:
                cooldown: 10
        listeners:
            SynchronizerListener:
                # to be altered by the platform-specific plugin; chat colours might not be the same.
                format: <%name%> %message%

lang: "en/us"
